#! /bin/sh
# /etc/init.d/goBot

### BEGIN INIT INFO
# Provides:          goBot
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting telegram"
    sudo python /home/pi/Documents/techlab_iot/script/telegramBot.py  >/tmp/botLog_error.txt 2>/tmp/botLog_normal.txt &
    ;;
  stop)
    echo "Stopping telegram"
    sudo kill -9 $(ps aux | grep '[t]elegramBot.py' | awk '{print $2}')
    sudo mv /tmp/botLog_normal.txt /tmp/botLog_normal.bak
    sudo mv /tmp/botLog_error.txt /tmp/botLog_error.bak
    ;;
  *)
    echo "Usage: /etc/init.d/goBot {start|stop}"
    exit 1
    ;;
esac

exit 0
