#!/bin/sh
### BEGIN INIT INFO
# Provides:          goBrain
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       The Brain!!!
### END INIT INFO

NAME="goBrain"

PROGRAM_PATH="/home/pi/Documents/bresso_iot/script/bressoBrain.py"
ERROR_PATH="/tmp/brainLog_error.txt"
LOG_PATH="/tmp/brainLog_normal.txt"
SCRIPT="python $PROGRAM_PATH >$ERROR_PATH 2>$LOG_PATH &"

RUNAS=root

start() {
  echo 'Starting service…' >&2
  su -c "$SCRIPT" $RUNAS
  echo 'Service started' >&2
}

stop() {
  echo 'Stopping service…' >&2
  kill -9 $(ps aux | grep "[p]ython $PROGRAM_PATH" | awk '{print $2}')
  mv $LOG_PATH $LOG_PATH.bak
  mv $ERROR_PATH $ERROR_PATH.bak
  echo 'Service stopped' >&2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  *)
    echo "Usage: $0 {start|stop}"
esac
