#! /bin/sh
# /etc/init.d/goPlot

### BEGIN INIT INFO
# Provides:          goPlot
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting the plot application"
    # run application you want to start
    sudo python /home/pi/Documents/techlab_iot/script/plotEnergy.py >/tmp/plotLog_error.txt 2>/tmp/plotLog_normal.txt &
    ;;
  stop)
    echo "Stopping the plot application"
    # kill application you want to stop
    sudo kill -9 $(ps aux | grep '[p]ython /home/pi/Documents/techlab_iot/script/plotEnergy.py' | awk '{print $2}')
    sudo mv /tmp/plotLog_normal.txt /tmp/plotLog_normal.bak
    sudo mv /tmp/plotLog_error.txt /tmp/plotLog_error.bak
    ;;
  *)
    echo "Usage: /etc/init.d/goPlot {start|stop}"
    exit 1
    ;;
esac

exit 0
